# Generated by Django 5.2.5 on 2025-11-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_verify_users', 'Может верифицировать пользователей'), ('can_manage_products', 'Может управлять товарами'), ('can_view_all_orders', 'Может просматривать все заказы')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('seller', 'Продавец'), ('admin', 'Админ')], default='customer', max_length=31),
        ),
    ]
