# Generated by Django 5.2.5 on 2025-11-24 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_verify_users', 'Может верифицировать пользователей'), ('can_manage_products', 'Может управлять товарами'), ('can_view_all_orders', 'Может просматривать все заказы')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='core.deliverymethod'),
        ),
    ]
